language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -U setuptools
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - ./bin/buildout -N -t 3 -c travis.cfg
script: ./bin/test
